version: "3"

services:
    app:
        build: .
        volumes:
            - ./src:/app
        ports:
            - "4000:4000"
        env_file:
            - .env
        # depends_on:
        #     - postgres
    # db:
    #     image: postgres:9.6
    #     environment:
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: postgres
    #         PGDATA: /var/lib/postgresql/data/pgdata
    #     restart: always
    #     volumes:
    #         - ./pgdata:/var/lib/postgresql/data
